import type { BuildProductsResult } from './build-products'
import type { BuildRecipesResult } from './build-recipes'
import type { BuildUnitsResult } from './build-units'
import type { ReviewQueue } from './review'

export interface ReportInput {
  units: BuildUnitsResult
  products: BuildProductsResult
  recipes: BuildRecipesResult
  queue: ReviewQueue
}

function bulletList (lines: string[], emptyText: string): string {
  if (lines.length === 0) return `${emptyText}\n`
  return `${lines.map((line) => `- ${line}`).join('\n')}\n`
}

export function buildReport (input: ReportInput): string {
  const { units, products, recipes, queue } = input

  const breakfastIds = new Set(
    products.products.filter((product) => product.category === 'breakfast').map((p) => p.id)
  )
  const breakfastRecipes = recipes.recipes.filter((recipe) => breakfastIds.has(recipe.productId))
  const choiceGroups = breakfastRecipes.reduce(
    (sum, recipe) =>
      sum + recipe.components.filter((component) => component.kind === 'choice').length,
    0
  )

  const productsByCategory = new Map<string, number>()
  for (const product of products.products) {
    productsByCategory.set(product.category, (productsByCategory.get(product.category) ?? 0) + 1)
  }

  const queueCounts = queue.countByType()
  const activeProducts = products.products.filter((product) => product.active).length
  const pendingItems = queue.items.filter((item) => item.status === 'pending')
  const resolvedItems = queue.items.filter((item) => item.status === 'resolved')

  const out: string[] = []
  out.push('# Migration report')
  out.push('')
  out.push('Generated by tools/migration. Do not edit by hand.')
  out.push('')
  out.push('## Summary')
  out.push('')
  out.push('| Metric | Count |')
  out.push('| --- | --- |')
  out.push(`| Kitchen units | ${units.units.length} |`)
  out.push(`| Duplicate units merged | ${units.duplicateMerges.length} |`)
  out.push(`| Unit names with embedded quantity | ${units.quantityApplied.length} |`)
  out.push(`| Presentation decorations skipped | ${units.presentation.length} |`)
  out.push(`| Products | ${products.products.length} |`)
  out.push(`| Products active | ${activeProducts} |`)
  out.push(`| Products inactive | ${products.products.length - activeProducts} |`)
  for (const [category, count] of [...productsByCategory.entries()].sort()) {
    out.push(`| Products, ${category} | ${count} |`)
  }
  out.push(`| Product duplicates merged | ${products.duplicateMerges.length} |`)
  out.push(`| Evaluation products missing in WP | ${products.missingInWp.length} |`)
  out.push(`| WP products excluded | ${products.excludedWp.length} |`)
  out.push(`| Recipes | ${recipes.recipes.length} |`)
  out.push(`| Breakfast recipes | ${breakfastRecipes.length} |`)
  out.push(`| Choice groups in breakfast recipes | ${choiceGroups} |`)
  out.push(`| Add-ons with recipe | ${recipes.addonsWithRecipe} |`)
  out.push(`| Products without recipe | ${recipes.productsWithoutRecipe.length} |`)
  out.push(`| Duplicate choices detected | ${recipes.duplicateChoices.length} |`)
  out.push(`| Review queue items | ${queue.items.length} |`)
  out.push(`| Review queue pending | ${pendingItems.length} |`)
  out.push(`| Review queue resolved | ${resolvedItems.length} |`)
  for (const [type, count] of Object.entries(queueCounts).sort()) {
    out.push(`| Review, ${type} | ${count} |`)
  }
  out.push('')

  out.push('## Duplicate units merged')
  out.push('')
  out.push(
    bulletList(
      units.duplicateMerges.map(
        (merge) =>
          `"${merge.mergedName}" merged into "${merge.keptName}" (${merge.refs.join(', ')})`
      ),
      'None.'
    )
  )

  out.push('## Quantity embedded in unit names')
  out.push('')
  out.push(
    bulletList(
      units.quantityApplied
        .filter((entry) => entry.quantity > 1)
        .map(
          (entry) =>
            `"${entry.rawName}" -> "${entry.baseName}" x${entry.quantity} (${entry.refs.join(', ')})`
        ),
      'None.'
    )
  )

  out.push('## Duplicate choices')
  out.push('')
  out.push(
    bulletList(
      recipes.duplicateChoices.map(
        (entry) => `${entry.breakfastName}: "${entry.groups[0]}" and "${entry.groups[1]}"`
      ),
      'None.'
    )
  )

  out.push('## Products without recipe')
  out.push('')
  out.push(
    bulletList(
      recipes.productsWithoutRecipe.map(
        (entry) => `"${entry.name}" (${entry.productId}, ${entry.category})`
      ),
      'None.'
    )
  )

  out.push('## Evaluation products missing in WordPress')
  out.push('')
  out.push(
    bulletList(
      products.missingInWp.map((entry) => `"${entry.name}" (${entry.id})`),
      'None.'
    )
  )

  out.push('## WP products excluded')
  out.push('')
  out.push(
    bulletList(
      products.excludedWp.map((entry) => `#${entry.id} "${entry.name}": ${entry.reason}`),
      'None.'
    )
  )

  out.push('## Unmapped decorations')
  out.push('')
  out.push(
    bulletList(
      recipes.unmappedDecorations.map(
        (entry) => `"${entry.name}" (${entry.breakfasts.join(', ')})`
      ),
      'None.'
    )
  )

  out.push('## Presentation decorations skipped')
  out.push('')
  out.push(
    bulletList(
      units.presentation.map((entry) => `"${entry.name}" (${entry.refs.join(', ')})`),
      'None.'
    )
  )

  out.push('## Resolved review items')
  out.push('')
  out.push(
    bulletList(
      resolvedItems.map(
        (item) => `${item.id}: ${item.resolution ?? 'resolved'} (${item.title})`
      ),
      'None.'
    )
  )

  out.push('## Notes')
  out.push('')
  out.push('- WP snapshot is the product master when data/wp-products.snapshot.json exists.')
  out.push('- Balloons are excluded by design (decision D6).')
  out.push('- A customer may include several breakfasts per order, each with its own option choices. Recipes model each choice as a group.')
  out.push('- Decisions live in data/review-decisions.json. Ids match data/review-queue.json.')
  out.push('- Review queue items with status auto-applied used the proposal. Set the id to reject to keep the original value.')
  out.push('- Review queue items with status pending need a decision.')
  out.push('')

  return out.join('\n')
}
