import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { readEnv } from './env'

const SOURCE_FILES = [
  'balloons.ts',
  'breakfasts.ts',
  'containers.ts',
  'decorations.ts',
  'extras.ts',
  'foods.ts',
  'products.ts',
  'types.ts',
]

const sourceDir = fileURLToPath(new URL('../source/', import.meta.url))

function sha256 (content: string): string {
  return createHash('sha256').update(content).digest('hex')
}

function gitCommit (repo: string): string {
  try {
    return execFileSync('git', ['-C', repo, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim()
  } catch {
    return ''
  }
}

async function main (): Promise<void> {
  const repo = readEnv('EVALUATION_REPO')
  if (!repo) {
    throw new Error(
      'Set EVALUATION_REPO in .env (path to the palorosa-breakfast-evaluation checkout)'
    )
  }

  await mkdir(sourceDir, { recursive: true })
  const files: Record<string, string> = {}
  for (const file of SOURCE_FILES) {
    const content = await readFile(join(repo, 'src', 'constants', file), 'utf8')
    await writeFile(join(sourceDir, file), content, 'utf8')
    files[file] = sha256(content)
  }

  try {
    const overrides = await readFile(join(repo, 'catalog', 'overrides.json'), 'utf8')
    await writeFile(join(sourceDir, 'overrides.json'), overrides, 'utf8')
    files['overrides.json'] = sha256(overrides)
  } catch {
    console.warn('No catalog/overrides.json in the source repo. Overrides skipped.')
  }

  const manifest = {
    source: 'palorosa-breakfast-evaluation',
    originPath: repo.replace(/\\/g, '/'),
    commit: gitCommit(repo),
    copiedAt: new Date().toISOString().slice(0, 10),
    note: 'Generated by pnpm sync:source. Read only. Do not edit. Canonical files: src/constants/* and catalog/overrides.json in the source repo.',
    files,
  }
  await writeFile(
    join(sourceDir, 'manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
    'utf8'
  )

  console.log('Source mirror updated')
  console.log(`  repo: ${repo}`)
  console.log(`  commit: ${manifest.commit || 'unknown'}`)
  console.log(`  files: ${Object.keys(files).length}`)
  console.log(`  destination: ${sourceDir}`)
}

await main()
