// Spanish end-user strings. The host and spectator surfaces share these; code
// and field names stay in English (D9).
export const labels = {
  loading: 'Cargando…',
  brand: 'Palorosa',
  appTitle: 'Panel de cocina',
  roleHost: 'Anfitrión',
  roleSpectator: 'Espectador',
  logout: 'Salir',

  tunnelStatus: {
    disabled: 'apagado',
    stopped: 'detenido',
    starting: 'conectando…',
    running: 'activo',
    errored: 'error',
  } as Record<string, string>,

  whatsappStatus: {
    connected: 'Conectado',
    connecting: 'Conectando…',
    disconnected: 'Desconectado',
    unlinked: 'Sin vincular',
    disabled: 'Apagado',
    off: 'Apagado',
  } as Record<string, string>,

  categories: {
    drink: 'Bebidas',
    main: 'Comidas',
    side: 'Acompañamientos',
    dessert: 'Postres',
    fruit: 'Frutas',
    condiment: 'Condimentos',
    other: 'Otros',
  } as Record<string, string>,

  // Kitchen measures. "unit" is the default and stays blank so the column only
  // shows something when a real measure was set.
  measures: {
    unit: '-',
    portion: 'Porción',
    glass: 'Vaso',
    bottle: 'Botella',
    slice: 'Tajada',
    spoon: 'Cucharada',
    gram: 'Gramo',
  } as Record<string, string>,

  invite: {
    title: 'Bienvenida a la cocina',
    intro: 'Para ver la lista del día necesitas una invitación del anfitrión.',
    token: 'Código o enlace de invitación',
    tokenHint: 'Pega aquí el código o el enlace',
    help: 'El anfitrión la genera en Ajustes → Invitaciones. Si abriste el enlace completo, entras directamente.',
    submit: 'Entrar',
    checking: 'Validando…',
    error: 'No pudimos validar la invitación. Pídele al anfitrión una nueva.',
  },

  nav: {
    resumen: 'Resumen',
    bots: 'Cuentas',
    destinos: 'Destinos',
    pedidos: 'Pedidos',
    lista: 'Lista',
    ajustes: 'Ajustes',
  },

  resumen: {
    bots: 'Cuentas conectadas',
    tunnel: 'Túnel',
    unitsToday: 'Unidades de hoy',
    nextSend: 'Próximo envío',
    noNextSend: 'Sin envíos programados',
    targets: '{n} destinos',
    activity: 'Actividad reciente',
    noActivity: 'Sin actividad todavía.',
    noOrders: 'Todavía no hay pedidos',
    access: 'Tu acceso',
    local: 'Esta máquina',
    remote: 'Otro dispositivo',
    listFor: 'Lista publicada',
    quick: 'Acciones rápidas',
    addAccount: 'Agregar cuenta',
    publishToday: 'Publicar lista de hoy',
    sendTest: 'Enviar prueba',
    published: 'Lista publicada.',
    testSent: 'Prueba enviada.',
    agoNow: 'ahora mismo',
    agoMinutes: 'hace {n} min',
    agoHours: 'hace {n} h',
    agoDays: 'hace {n} d',
  },

  lista: {
    empty: 'No hay pedidos para este día.',
    print: 'Imprimir',
    copy: 'Copiar',
    copied: 'Lista copiada',
    copyFailed: 'No pudimos copiar la lista.',
    title: 'Lista de cocina',
    unresolved: 'Sin resolver',
    review: 'Revisar',
    quantity: 'Cantidad',
    product: 'Producto',
    measure: 'Medida',
    note: 'Nota',
    unresolvedOne: '1 línea sin resolver',
    unresolvedMany: '{n} líneas sin resolver',
    unresolvedHint: 'Confirma el producto antes de preparar el pedido.',
    unresolvedReasons: {
      unknown_product: 'Producto no reconocido',
      missing_recipe: 'Producto sin receta',
      missing_choice: 'Opción no reconocida',
      ambiguous_match: 'Coincidencia ambigua',
      missing_unit: 'Unidad no encontrada',
    } as Record<string, string>,
  },

  day: {
    label: 'Día',
    today: 'Hoy',
    tomorrow: 'Mañana',
    pick: 'Elegir otra fecha',
  },

  sync: {
    button: 'Actualizar',
    running: 'Actualizando…',
    hint: 'Ejecuta el export de pedidos de la tienda para hoy, mañana y el día elegido. Tarda un poco.',
    done: 'Pedidos actualizados ({n} para este día)',
    last: 'Actualizado',
    never: 'nunca',
    justNow: 'hace un momento',
    minutes: 'hace {n} min',
    every: 'cada {n} min',
    failed: 'No se pudo actualizar (pasa el cursor para ver el motivo)',
  },

  pedidos: {
    empty: 'No hay pedidos para este día.',
    remove: 'Quitar',
    units: '{n} unidades',
    pending: 'En proceso',
    notified: 'Avisado',
    today: 'Hoy',
    tomorrow: 'Mañana',
    search: 'Buscar por pedido…',
    noResults: 'Ningún pedido coincide con la búsqueda.',
    note: 'Observación:',
    unitsWord: 'unidades',
    ordersWord: 'pedidos',
    showAllUnits: 'Mostrar todas las unidades',
    showFewerUnits: 'Mostrar menos',
    loadingDetail: 'Cargando…',
    attach: 'Adjuntar',
    attachTitle: 'Adjuntar pedidos',
    attachHint: 'Marca variantes para juntar en un solo ticket los pedidos que coinciden. También puedes seleccionar tickets a mano.',
    attachClear: 'Limpiar filtros',
    attachEmpty: 'No hay variantes para filtrar.',
    selectTicket: 'Seleccionar este pedido',
    selectedCount: '{n} seleccionados',
    attachCancel: 'Cancelar',
    attachSelected: 'Adjuntar en un ticket',
    attachTwo: 'Adjunta al menos 2 pedidos.',
    attachedByFilter: 'Adjuntado por filtros',
    attachedGroup: '{n} pedidos en un ticket',
    separate: 'Separar',
    noFilterResults: 'Ningún pedido coincide con las variantes marcadas.',
    facetKinds: {
      breakfast: 'Desayuno',
      add_on: 'Adicionales',
      color: 'Color',
      other: 'Otros',
    } as Record<string, string>,
  },

  bots: {
    account: 'Cuenta',
    status: 'Estado',
    allowlist: 'Números autorizados',
    noAllowlist: 'Sin números autorizados.',
    preview: 'Cada cuenta atiende la misma cocina: los pedidos que recibe cualquiera se ven en todos.',
    pairing: 'La vinculación se hace desde el programa de la cocina o pidiendo un código QR aquí.',
    add: 'Agregar cuenta',
    name: 'Nombre',
    numbers: 'Números (separados por coma)',
    numbersHint: 'Números autorizados, separados por coma.',
    noNumber: 'Sin número vinculado',
    linked: 'Vinculado',
    remove: 'Quitar',
    removeConfirm: '¿Quitar esta cuenta?',
    edit: 'Editar cuenta',
    enabled: 'Cuenta activa',
    save: 'Guardar',
    saved: 'Cuenta guardada.',
    retry: 'Reintentar vinculación',
    logout: 'Cerrar sesión de WhatsApp',
    logoutConfirm: '¿Cerrar la sesión de WhatsApp de esta cuenta? Tendrás que vincularla otra vez.',
    scan: 'Escanea este código con WhatsApp',
  },

  destinos: {
    note: 'Los avisos por número tienen su horario y horas de silencio. Los envía la cuenta de la cocina.',
    target: 'Destino',
    events: 'Eventos',
    global: 'Destino',
    label: 'Etiqueta',
    phone: 'Número',
    bot: 'Cuenta que envía',
    botAuto: 'Automático',
    kindsNew: 'Pedidos nuevos',
    kindsUpdated: 'Cambios de pedido',
    kindToday: 'Para hoy',
    kindTomorrow: 'Para mañana',
    modeImmediate: 'Inmediato',
    modeTimes: 'Por horas',
    times: 'Horas',
    addTime: 'Agregar hora',
    quiet: 'Silencio',
    quietFrom: 'Desde',
    quietTo: 'Hasta',
    add: 'Agregar destino',
    newTarget: 'Nuevo destino',
    editTarget: 'Editar destino',
    save: 'Guardar',
    saved: 'Destino guardado.',
    test: 'Enviar prueba',
    testSent: 'Prueba enviada.',
    remove: 'Quitar',
    removeConfirm: '¿Quitar este destino?',
    enabled: 'Activo',
    disabled: 'Apagado',
    empty: 'Todavía no hay destinos.',
    immediate: 'Inmediato',
  },

  ajustes: {
    store: 'Tienda',
    domain: 'Dominio',
    tunnelHostname: 'Hostname del túnel',
    adminUrl: 'URL de WordPress',
    adminUrlHint: 'Opcional. Si lo dejas vacío se usa el dominio de la tienda; también vale pegar el enlace de /wp-admin.',
    loginTest: 'Probar inicio de sesión',
    loginTesting: 'Probando…',
    loginResult: { ok: 'Inicio de sesión correcto', warn: 'Aviso', fail: 'No se pudo iniciar sesión', skipped: 'Omitido' },
    adminUser: 'Usuario',
    adminPassword: 'Contraseña',
    consumerKey: 'Consumer key',
    consumerSecret: 'Consumer secret',
    exportId: 'Export ID',
    exportCronKey: 'Cron key',
    webhookSecret: 'Webhook secret',
    keepHint: 'Déjalo vacío para conservar el valor actual.',
    save: 'Guardar',
    saved: 'Ajustes guardados.',
    saveRestart: 'Guardar y reiniciar',
    restarting: 'Reiniciando…',
    notifications: 'Avisos',
    notifEnabled: 'Avisos generales',
    notifNew: 'Pedidos nuevos',
    notifUpdated: 'Cambios de pedido',
    notifToday: 'Para hoy',
    notifTomorrow: 'Para mañana',
    autostart: 'Abrir al iniciar Windows',
    advanced: 'Avanzado',
    syncMinutes: 'Actualizar pedidos cada (minutos)',
    syncMinutesHint: 'Ejecuta el export de pedidos de la tienda (hoy y mañana) cada tantos minutos. 0 lo desactiva; el botón Actualizar sigue funcionando. Se aplica sin reiniciar.',
    restartHint: 'El túnel, el puerto, la ruta del catálogo y el modo diagnóstico se aplican al reiniciar. Usa "Guardar y reiniciar" para aplicarlos sin cerrar la aplicación a mano.',
    catalogPath: 'Ruta del catálogo',
    panelPort: 'Puerto del panel',
    debug: 'Modo diagnóstico',
    saveAdvanced: 'Guardar avanzado',
    savedAdvanced: 'Ajustes avanzados guardados.',
    diagnostics: 'Diagnóstico',
    version: 'Versión',
    uptime: 'En marcha',
    dataDir: 'Datos',
    updates: 'Actualizaciones',
    updatesHint: 'La aplicación se actualiza sola desde GitHub Releases al abrir y cada 6 horas.',
    updateCheck: 'Buscar actualización',
    updateChecking: 'Buscando…',
    updateApply: 'Actualizar y reiniciar',
    updateApplying: 'Descargando e instalando…',
    updateIdle: 'Sin comprobar todavía.',
    updateUpToDate: (version: string) => `Última versión instalada (${version}).`,
    updateAvailable: (latest: string) => `Hay una versión ${latest} disponible.`,
    updateInstalled: (latest: string) => `Versión ${latest} instalada. La aplicación se está reiniciando…`,
    updateError: (message: string) => `No se pudo actualizar: ${message}`,
    logs: 'Registros recientes',
    logsEmpty: 'Sin registros todavía.',
    logsHelp: 'Se guardan en app.log dentro de la carpeta de datos; al pasar de 2 MB el anterior se renombra a app.log.1.',
    showLogs: 'Ver últimos',
    hideLogs: 'Ocultar',
    refreshLogs: 'Actualizar',
    exportLogs: 'Exportar',
    logsExported: 'Registros exportados',
    config: 'Copia de la configuración',
    configHelp: 'Descarga un archivo con toda la configuración (incluidas las claves) para llevarla a otro PC. Guárdalo en un sitio seguro: contiene contraseñas.',
    exportConfig: 'Exportar configuración',
    importConfig: 'Importar configuración',
    configExported: 'Configuración exportada',
    configImported: 'Configuración importada',
    importConfirm: 'Esto reemplaza la configuración actual de este equipo. ¿Continuar?',
    openLogFolder: 'Abrir carpeta (en el PC)',
    logsFolderOpened: 'Carpeta abierta en el PC de la cocina',
    copyLogs: 'Copiar',
    logsCopied: 'Registros copiados',
    checks: 'Comprobaciones',
    checksHint: 'Prueba cada pieza que la cocina necesita. Las pruebas no cambian pedidos: el webhook envía un pedido de muestra firmado que se valida y se descarta.',
    checksRunAll: 'Probar todo',
    checksRunning: 'Probando…',
    checksRun: 'Probar',
    checksNever: 'Sin probar',
    checksSummary: (ok: number, warn: number, fail: number) => `${ok} bien · ${warn} con avisos · ${fail} fallando`,
    checkStatus: { ok: 'Funciona', warn: 'Aviso', fail: 'Falla', skipped: 'Omitida', '': 'Sin probar' } as Record<string, string>,
    tunnel: 'Túnel de Cloudflare',
    tunnelStatus: 'Estado',
    tunnelAuth: 'Autenticación',
    tunnelCert: 'Certificado de cloudflared',
    tunnelPresent: 'presente',
    tunnelMissing: 'falta: ejecuta "cloudflared tunnel login" o configura un token',
    tunnelToken: 'Token del túnel',
    tunnelTokenHint: 'Para pasar el túnel a otro PC sin hacer login: en el PC actual ejecuta "cloudflared tunnel token palorosa-kitchen" y pega aquí el valor (o impórtalo con la configuración).',
    tunnelTokenSet: 'token del túnel configurado',
    tunnelLogin: 'Iniciar sesión de cloudflared',
    tunnelLoginStarted: 'Se abrió el navegador para autorizar el túnel.',
    tunnelCopy: 'Copiar URL',
    invites: 'Invitaciones',
    inviteLabel: 'Para quién',
    inviteCreate: 'Crear invitación',
    inviteLink: 'Enlace para compartir',
    copyInviteLink: 'Copiar enlace',
    copyInviteCode: 'Copiar código',
    inviteLinkCopied: 'Enlace copiado',
    inviteCodeCopied: 'Código copiado',
    copyFailed: 'No se pudo copiar',
    inviteEmpty: 'No hay invitaciones pendientes.',
    sessions: 'Espectadores conectados',
    sessionsEmpty: 'Todavía no hay nadie conectado.',
    revoke: 'Quitar',
    createdAt: 'Creada',
    expiresAt: 'Vence',
    lastSeen: 'Última vez',
  },

  errors: {
    load: 'No pudimos cargar los datos.',
  },

  push: {
    title: 'Avisos en este dispositivo',
    enable: 'Activar avisos',
    disable: 'Desactivar avisos',
    enabled: 'Activados',
    off: 'Desactivados',
    hint: 'Recibe un aviso aquí cuando llegue un pedido.',
    unsupported: 'Este navegador no permite avisos.',
    desktopOn: 'Activados en este PC',
    desktopHint: 'Cada pedido nuevo muestra una notificación de Windows.',
    working: 'Activando…',
    denied: 'No diste permiso para los avisos. Inténtalo de nuevo y acepta el permiso.',
    blocked: 'Los avisos están bloqueados en este navegador. Habilítalos en los ajustes del sitio.',
    unavailable: 'El servidor no tiene los avisos activados.',
    failed: 'No pudimos activar los avisos.',
  },
}
